#!/usr/bin/env python3
"""Render the branch-specific packaged-E2E profile from matrix plus scenario contract."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "e2e"))

import branch_readme  # noqa: E402
import matrix as release_matrix  # noqa: E402
from scenario_contract import load_contract  # noqa: E402


START_MARKER = "<!-- e2e-branch-profile:start -->"
END_MARKER = "<!-- e2e-branch-profile:end -->"


class E2EReadmeError(ValueError):
    pass


def render_profile(
    matrix: Mapping[str, Any], *, profile_branch: str, contract_path: Path
) -> str:
    if matrix.get("schema_version") == 3:
        project = matrix.get("project")
        release_branch = project.get("release_branch") if isinstance(project, Mapping) else None
        if release_branch != "master":
            raise E2EReadmeError("unified source matrix must name master")
    else:
        release_branch = branch_readme.extract_branch_facts(matrix).release_branch
    if profile_branch != "master" and profile_branch != release_branch:
        raise E2EReadmeError(
            f"profile branch {profile_branch!r} does not match "
            f"matrix release branch {release_branch!r}"
        )
    contract = load_contract(contract_path)
    artifacts = matrix.get("artifacts")
    runtimes = matrix.get("runtimes")
    if not isinstance(artifacts, list) or not isinstance(runtimes, list):
        raise E2EReadmeError("matrix artifacts and runtimes must be arrays")
    runtime_by_node = {
        runtime.get("artifact_node"): runtime
        for runtime in runtimes
        if isinstance(runtime, Mapping)
    }
    if len(runtime_by_node) != len(runtimes):
        raise E2EReadmeError("matrix runtime identities are invalid or duplicated")

    label = ("shared source" if matrix.get("schema_version") == 3 else
             "integration baseline" if profile_branch == "master" else "release branch")
    lines = [
        START_MARKER,
        "<!-- Generated by scripts/release/e2e_readme.py; edit matrix/contract, not this block. -->",
        f"This `{profile_branch}` {label} exercises the following exact packaged lanes:",
        "",
        "| Artifact | Minecraft | Loader | Java | Contract scenarios |",
        "|---|---:|---|---:|---:|",
    ]
    for raw_artifact in artifacts:
        if not isinstance(raw_artifact, Mapping):
            raise E2EReadmeError("matrix artifact must be an object")
        node = raw_artifact.get("artifact_node")
        runtime = runtime_by_node.get(node)
        if not isinstance(node, str) or not isinstance(runtime, Mapping):
            raise E2EReadmeError("each artifact must have one runtime")
        lines.append(
            f"| `{node}` | `{raw_artifact.get('artifact_version')}` | "
            f"{release_matrix.LOADER_DISPLAY_NAMES.get(str(raw_artifact.get('loader')), raw_artifact.get('loader'))} | "
            f"`{raw_artifact.get('java')}` | `{len(contract.scenarios)}` |"
        )

    lines.extend(
        (
            "",
            f"Scenario contract SHA-256: `{contract.sha256}`",
            (
                "Contract totals: "
                f"`{sum(len(role.steps) for scenario in contract.scenarios for role in scenario.roles)}` "
                "ordered steps, "
                f"`{sum(step.capture is not None for scenario in contract.scenarios for role in scenario.roles for step in role.steps)}` "
                "captures."
            ),
            "",
            "| Scenario | Profiles | Orchestration | Roles | Ordered steps | Captures |",
            "|---|---|---|---|---:|---:|",
        )
    )
    for scenario in contract.scenarios:
        step_count = sum(len(role.steps) for role in scenario.roles)
        capture_count = sum(
            step.capture is not None for role in scenario.roles for step in role.steps
        )
        lines.append(
            f"| `{scenario.scenario}` | "
            f"{', '.join(f'`{profile}`' for profile in scenario.execution_profiles)} | "
            f"`{scenario.orchestration.mode}` | "
            f"{', '.join(f'`{role.role}`' for role in scenario.roles)} | "
            f"`{step_count}` | `{capture_count}` |"
        )
    lines.extend(
        (
            "",
            "`e2e/scenario-contract.json` is the sole source for scenario ids, execution "
            "profiles, launch topology, steps, assertions, captures, probes, and comparisons. "
            "Screenshot emission is exact: each role step must emit a screenshot if and only "
            "if its contract entry declares `capture`. Version/loader/Java/runtime pins come "
            "only from this branch's validated release matrix.",
            END_MARKER,
        )
    )
    return "\n".join(lines)


def replace_profile(readme: str, rendered: str) -> str:
    if readme.count(START_MARKER) != 1 or readme.count(END_MARKER) != 1:
        raise E2EReadmeError("E2E README must contain exactly one generated profile marker pair")
    start = readme.index(START_MARKER)
    end_start = readme.index(END_MARKER, start)
    if end_start < start:
        raise E2EReadmeError("E2E README profile markers are out of order")
    end = end_start + len(END_MARKER)
    return readme[:start] + rendered + readme[end:]


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--matrix", type=Path, default=Path("release/release-matrix.json"))
    parser.add_argument("--contract", type=Path, default=Path("e2e/scenario-contract.json"))
    parser.add_argument("--readme", type=Path, default=Path("e2e/README.md"))
    parser.add_argument("--profile-branch", required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        matrix = release_matrix.load_matrix(args.matrix)
        rendered = render_profile(
            matrix, profile_branch=args.profile_branch, contract_path=args.contract
        )
        current = args.readme.read_text(encoding="utf-8")
        expected = replace_profile(current, rendered)
        if args.check:
            if current != expected:
                raise E2EReadmeError("E2E README generated profile is stale")
        else:
            args.readme.write_text(expected, encoding="utf-8")
    except (OSError, ValueError) as exc:
        print(f"E2E README profile error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
