#!/usr/bin/env python3
"""Generate README support rows and gate badges from authoritative release matrices.

Shared source uses --matrix directly. Historical branch layouts retain the stdin/Git-ref reader;
neither mode owns a second list of supported Minecraft versions or loaders.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any
from urllib.parse import quote

import matrix as release_matrix
import version_branches


START_MARKER = "<!-- release-status:start -->"
END_MARKER = "<!-- release-status:end -->"
REPOSITORY = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")


class StatusTableError(ValueError):
    pass


def load_matrix_from_ref(branch: str, *, ref_prefix: str) -> dict[str, Any]:
    ref = f"{ref_prefix}{branch}"
    try:
        result = subprocess.run(
            ["git", "show", f"{ref}:release/release-matrix.json"],
            check=True,
            capture_output=True,
            text=True,
        )
        data = json.loads(result.stdout)
    except (subprocess.CalledProcessError, json.JSONDecodeError) as exc:
        raise StatusTableError(f"cannot read release matrix from {ref}: {exc}") from exc
    if not isinstance(data, dict):
        raise StatusTableError(f"release matrix on {branch} is not an object")
    release_matrix.validate_matrix(data)
    return data


def release_metadata(branch: str, data: Mapping[str, Any]) -> tuple[str, str, str]:
    parsed = version_branches.parse_version_branch(branch)
    if parsed is None:
        raise StatusTableError(f"not a version branch: {branch}")
    artifacts = data.get("artifacts")
    if not isinstance(artifacts, list) or not artifacts:
        raise StatusTableError(f"{branch} has no release artifacts")

    versions = {str(artifact.get("artifact_version", "")) for artifact in artifacts}
    if versions != {parsed.version}:
        raise StatusTableError(
            f"{branch} names {parsed.version} but its matrix declares {sorted(versions)!r}"
        )
    loaders = tuple(dict.fromkeys(str(artifact.get("loader")) for artifact in artifacts))
    if set(loaders) != set(parsed.loaders) or len(loaders) != len(parsed.loaders):
        raise StatusTableError(
            f"{branch} loaders in name {parsed.loaders!r} disagree with matrix {loaders!r}"
        )
    java_versions = {artifact.get("java") for artifact in artifacts}
    if len(java_versions) != 1:
        raise StatusTableError(f"{branch} artifacts disagree on Java: {java_versions!r}")

    display_loaders = " + ".join(
        release_matrix.LOADER_DISPLAY_NAMES.get(loader, loader) for loader in loaders
    )
    return parsed.version, display_loaders, str(next(iter(java_versions)))


def workflow_badge(repository: str, branch: str, workflow: str, label: str) -> str:
    encoded_branch = quote(branch, safe="")
    encoded_query = quote(f"branch:{branch}", safe="")
    image = (
        f"https://github.com/{repository}/actions/workflows/{workflow}/badge.svg"
        f"?branch={encoded_branch}"
    )
    target = (
        f"https://github.com/{repository}/actions/workflows/{workflow}"
        f"?query={encoded_query}"
    )
    return f"[![{label}]({image})]({target})"


def render_status_section(
    branch_matrices: Mapping[str, Mapping[str, Any]], *, repository: str
) -> str:
    if not REPOSITORY.fullmatch(repository):
        raise StatusTableError(f"invalid GitHub repository: {repository}")
    parsed = []
    seen_versions: set[str] = set()
    for branch, data in branch_matrices.items():
        branch_info = version_branches.parse_version_branch(branch)
        if branch_info is None:
            raise StatusTableError(f"not a version branch: {branch}")
        if branch_info.version in seen_versions:
            raise StatusTableError(
                f"multiple release branches declare Minecraft {branch_info.version}"
            )
        seen_versions.add(branch_info.version)
        parsed.append((branch_info, data))
    if not parsed:
        raise StatusTableError("no release branches were discovered")

    lines = [
        START_MARKER,
        "<!-- Generated by scripts/release/status_table.py; do not edit this block manually. -->",
        "| Minecraft | Loaders | Java | Build | Packaged E2E | Branch |",
        "|---|---|---:|:---:|:---:|---|",
    ]
    for branch_info, data in sorted(
        parsed, key=lambda item: item[0].version_key, reverse=True
    ):
        version, loaders, java = release_metadata(branch_info.name, data)
        build = workflow_badge(
            repository,
            branch_info.name,
            "build-gate.yml",
            f"Build {version}",
        )
        e2e = workflow_badge(
            repository,
            branch_info.name,
            "on-demand-e2e.yml",
            f"E2E {version}",
        )
        branch_url = f"https://github.com/{repository}/tree/{quote(branch_info.name, safe='')}"
        lines.append(
            f"| {version} | {loaders} | {java} | {build} | {e2e} | "
            f"[`{branch_info.name}`]({branch_url}) |"
        )
    lines.append(END_MARKER)
    return "\n".join(lines)


def render_shared_status_section(
    data: dict[str, Any], *, repository: str, mod_version: str
) -> str:
    release_matrix.validate_matrix(data)
    if data.get("schema_version") != 3:
        raise StatusTableError("shared-source status requires a schema-3 matrix")
    if not REPOSITORY.fullmatch(repository):
        raise StatusTableError(f"invalid GitHub repository: {repository}")
    branch = data["project"]["release_branch"]
    branch_url = f"https://github.com/{repository}/tree/{quote(branch, safe='')}"
    build = workflow_badge(repository, branch, "build-gate.yml", "Shared build")
    e2e = workflow_badge(repository, branch, "on-demand-e2e.yml", "Shared packaged E2E")
    lines = [
        START_MARKER,
        "<!-- Generated by scripts/release/status_table.py; do not edit this block manually. -->",
        f"All targets use [`{branch}`]({branch_url}). These badges report the shared source gates:",
        "",
        f"{build} {e2e}",
        "",
        "Each target has an independent canonical release tag; listing a tag does not imply it is published.",
        "",
        "| Minecraft | Loaders | Java | Release tag |",
        "|---|---|---:|---|",
    ]
    versions = {row["artifact_version"] for row in data["artifacts"]}
    for version in sorted(versions, key=lambda value: tuple(map(int, value.split("."))), reverse=True):
        rows = [row for row in data["artifacts"] if row["artifact_version"] == version]
        loaders = " + ".join(release_matrix.LOADER_DISPLAY_NAMES[name]
                             for name in dict.fromkeys(row["loader"] for row in rows))
        java_versions = sorted({row["java"] for row in rows})
        java = " / ".join(str(value) for value in java_versions)
        tag = release_matrix.release_id(data, mod_version, target=version)
        tag_url = f"https://github.com/{repository}/releases/tag/{quote(tag, safe='')}"
        lines.append(f"| {version} | {loaders} | {java} | [`{tag}`]({tag_url}) |")
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_status_section(readme: str, section: str) -> str:
    if readme.count(START_MARKER) != 1 or readme.count(END_MARKER) != 1:
        raise StatusTableError("README must contain exactly one release-status marker pair")
    start = readme.index(START_MARKER)
    try:
        end = readme.index(END_MARKER, start) + len(END_MARKER)
    except ValueError as exc:
        raise StatusTableError("README release-status markers are out of order") from exc
    return f"{readme[:start]}{section}{readme[end:]}"


def load_discovered_matrices(
    names: Iterable[str], *, ref_prefix: str
) -> dict[str, dict[str, Any]]:
    branches = version_branches.discover_version_branches(names, exclude={"master"})
    if not branches:
        raise StatusTableError("no release branches were discovered")
    return {
        branch: load_matrix_from_ref(branch, ref_prefix=ref_prefix)
        for branch in branches
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository", required=True, help="GitHub OWNER/REPOSITORY")
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    parser.add_argument("--matrix", type=Path,
                        help="shared-source matrix; supplied directly without reading branch names or Git refs")
    parser.add_argument(
        "--ref-prefix",
        default="refs/remotes/origin/",
        help="Git ref prefix containing every discovered branch",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        if args.matrix is not None:
            data = release_matrix.load_matrix(args.matrix)
            section = render_shared_status_section(data, repository=args.repository,
                mod_version=release_matrix.read_mod_version(args.matrix, data))
        else:
            matrices = load_discovered_matrices(sys.stdin, ref_prefix=args.ref_prefix)
            section = render_status_section(matrices, repository=args.repository)
        original = args.readme.read_text(encoding="utf-8")
        updated = replace_status_section(original, section)
    except (OSError, StatusTableError, release_matrix.MatrixError) as exc:
        parser.error(str(exc))

    if args.check:
        if updated != original:
            print(f"{args.readme} release status table is stale", file=sys.stderr)
            return 1
    elif args.write:
        if updated != original:
            args.readme.write_text(updated, encoding="utf-8")
    else:
        sys.stdout.write(updated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
